### ISSUE TITLE
windows环境下遇到的问题

### ISSUE THREAD

**Issue by LoganZhuZzz** [hcsp/practise-java-commands#191]
@blindpirate 
虽然PR通过了，但我本地执行test的时候并没有通过
当我在cmd中编译，运行是完全没有问题
![image](https://user-images.githubusercontent.com/76999207/108473878-90e74280-72c9-11eb-8a2c-97e14c4c5ade.png)
当我用gitbash运行字节码文件时报出以下错误
![image](https://user-images.githubusercontent.com/76999207/108474003-baa06980-72c9-11eb-984c-28e16760c7bf.png)
是否是因为win环境下分隔符用 ; linux环境下用 : 无法兼容??? 
运行test时，其他两个脚本完全没问题，但是提到的这个不行
![image](https://user-images.githubusercontent.com/76999207/108474354-36021b00-72ca-11eb-95fb-b04e8299c9b2.png)
麻烦张博大佬给我解答下疑问

**Comment by blindpirate** [comment]
@zeq96 

这是因为windows上面的分隔符是分号，所以需要`java -cp xx.jar;. StringIsBlank x y z`

但是，在bash中运行时，分号是bash的命令分隔符，所以必须对分号进行转义，即

`java -cp 'xx.jar;.' StringIsBlank x y z`

或者

`java -cp xx.jar\;. StringIsBlank x y z`
